"""Piper TTS training and inference via isolated subprocess."""
import asyncio
import csv
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import scipy.signal as sps
import soundfile as sf

_PROJECT_ROOT = Path(__file__).parent.parent.parent
PIPER_VENV    = _PROJECT_ROOT / "piper_venv"
PIPER_CKPTS   = _PROJECT_ROOT / "piper_checkpoints"
_SR           = 22050
_IS_WIN       = sys.platform == "win32"


def _python() -> Path:
    return PIPER_VENV / ("Scripts/python.exe" if _IS_WIN else "bin/python")


def _piper_bin() -> Path:
    return PIPER_VENV / ("Scripts/piper.exe" if _IS_WIN else "bin/piper")


def can_infer() -> bool:
    return _piper_bin().exists()


def can_train() -> bool:
    """True if the piper venv has everything needed to start training."""
    return diagnose() is None


def diagnose() -> str | None:
    """Human-readable reason piper training isn't available, or None if ready."""
    py = _python()
    if not py.exists():
        return f"piper venv not found at {PIPER_VENV} — run the setup script."

    check = "phonemizer" if _IS_WIN else "piper_train"
    try:
        r = subprocess.run(
            [str(py), "-c", f"import {check}"],
            capture_output=True, timeout=15, text=True,
        )
    except Exception as exc:
        return f"couldn't run the piper venv's python ({exc}) — rerun the setup script."

    if r.returncode != 0:
        lines = (r.stderr or r.stdout or "").strip().splitlines()
        detail = lines[-1] if lines else f"exit code {r.returncode}"
        if "No Python at" in detail:
            return (
                f"the piper venv is broken ({detail}) — it was likely created with a "
                "different Python (e.g. from WSL). Delete piper_venv/ and rerun the "
                "setup script."
            )
        return f"{detail} — rerun the setup script."
    return None


def is_ready() -> bool:
    return can_infer()


# ── piper_phonemize shim ──────────────────────────────────────────────────────
# On Windows, piper-phonemize (C extension) can't be compiled without dev headers.
# We drop a pure-Python shim into the venv that satisfies piper-train's import
# using the `phonemizer` package (which calls the espeak-ng binary directly).

_SHIM_CODE = r'''
"""
piper_phonemize shim.
Replaces the C extension with phonemizer (calls espeak-ng binary).
Implements the same Python-level API as piper_phonemize 1.1.0's __init__.py
(see https://github.com/rhasspy/piper-phonemize/blob/v1.1.0/piper_phonemize/__init__.py)
so piper_train.preprocess's `from piper_phonemize import (...)` succeeds and
produces phoneme IDs compatible with the pretrained checkpoint's embeddings.
Auto-generated by Faily — do not edit.
"""
import json, os, shutil
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ── locate espeak-ng binary ───────────────────────────────────────────────────
def _ensure_espeak_path():
    if shutil.which("espeak-ng"):
        return
    for candidate in [
        r"C:\Program Files\eSpeak NG",
        r"C:\Program Files (x86)\eSpeak NG",
    ]:
        if Path(candidate).is_dir():
            os.environ["PATH"] = candidate + os.pathsep + os.environ.get("PATH", "")
            return

_ensure_espeak_path()


# ── phoneme ID map (loaded from piper config JSON) — must match the base
# checkpoint's embedding table exactly, so we read it from the voice config
# rather than hardcoding it. ──────────────────────────────────────────────────
def _load_phoneme_id_map() -> Dict[str, List[int]]:
    here = Path(__file__).resolve()
    for parent in here.parents:
        cfgs = list((parent / "piper_checkpoints").glob("*.onnx.json"))
        if cfgs:
            try:
                data = json.loads(cfgs[0].read_text(encoding="utf-8"))
                if "phoneme_id_map" in data:
                    return data["phoneme_id_map"]
            except Exception:
                pass
    return {}

DEFAULT_PHONEME_ID_MAP: Dict[str, List[int]] = _load_phoneme_id_map()
_PAD, _BOS, _EOS = "_", "^", "$"


# ── IPA tokenizer ─────────────────────────────────────────────────────────────
def _tokenize(ipa: str) -> List[str]:
    """Greedily split IPA string into tokens present in the phoneme map."""
    keys = sorted(DEFAULT_PHONEME_ID_MAP, key=len, reverse=True)
    tokens, i = [], 0
    while i < len(ipa):
        for k in keys:
            if ipa[i : i + len(k)] == k:
                tokens.append(k)
                i += len(k)
                break
        else:
            i += 1
    return tokens


# ── main API ──────────────────────────────────────────────────────────────────
def phonemize_espeak(
    text: str,
    voice: str = "en-us",
    data_path=None,
) -> List[List[str]]:
    """
    Convert text to IPA phoneme token lists using phonemizer + espeak-ng.
    Matches the API of the real piper_phonemize C extension.
    """
    from phonemizer.backend import EspeakBackend
    from phonemizer.separator import Separator

    backend = EspeakBackend(
        voice,
        with_stress=True,
        language_switch="remove-flags",
        words_mismatch="ignore",
    )
    sep = Separator(phone=None, word=" ", syllable="")
    sentences = [s for s in text.split("\n") if s.strip()] or [text]
    ipa_list = backend.phonemize(sentences, separator=sep, strip=True)
    return [_tokenize(s) for s in ipa_list]


def phonemize_codepoints(text: str, casing: str = "fold") -> List[List[str]]:
    """Phonemize text as raw UTF-8 codepoints (--phoneme-type text mode)."""
    if casing == "lower":
        text = text.lower()
    elif casing == "upper":
        text = text.upper()
    elif casing == "fold":
        text = text.casefold()
    sentences = [s for s in text.split("\n") if s.strip()] or [text]
    return [list(s) for s in sentences]


def _phonemes_to_ids(phonemes: List[str]) -> Tuple[List[int], Dict[str, int]]:
    """Mirrors piper_phonemize's phonemes_to_ids: BOS, pad-interspersed
    phonemes (pad after every phoneme, including the last), then EOS."""
    ids: List[int] = []
    missing: Dict[str, int] = {}
    pad_ids = DEFAULT_PHONEME_ID_MAP.get(_PAD, [0])

    ids.extend(DEFAULT_PHONEME_ID_MAP.get(_BOS, [1]))
    ids.extend(pad_ids)
    for p in phonemes:
        mapped = DEFAULT_PHONEME_ID_MAP.get(p)
        if mapped is None:
            missing[p] = missing.get(p, 0) + 1
            continue
        ids.extend(mapped)
        ids.extend(pad_ids)
    ids.extend(DEFAULT_PHONEME_ID_MAP.get(_EOS, [2]))
    return ids, missing


def phoneme_ids_espeak(
    phonemes: List[str],
    missing_phonemes: Optional[object] = None,
) -> List[int]:
    ids, missing = _phonemes_to_ids(phonemes)
    if missing_phonemes is not None and missing:
        missing_phonemes.update(missing)
    return ids


def phoneme_ids_codepoints(
    language: str,
    phonemes: List[str],
    missing_phonemes: Optional[object] = None,
) -> List[int]:
    # Faily only trains with espeak-derived phonemes; codepoints mode isn't
    # exercised, but the symbol must exist for piper_train's import to succeed.
    ids, missing = _phonemes_to_ids(phonemes)
    if missing_phonemes is not None and missing:
        missing_phonemes.update(missing)
    return ids


def get_espeak_map() -> Dict[str, List[int]]:
    return DEFAULT_PHONEME_ID_MAP


def get_codepoints_map() -> Dict[str, Dict[str, List[int]]]:
    return {}


def get_max_phonemes() -> int:
    return 256


def tashkeel_run(text: str, tashkeel_model=None) -> str:
    # Arabic diacritization — not used for English training.
    return text
'''


def _site_packages() -> Path:
    """Return the site-packages directory inside the piper venv."""
    if _IS_WIN:
        return PIPER_VENV / "Lib" / "site-packages"
    lib = PIPER_VENV / "lib"
    py_dirs = sorted(lib.glob("python3.*"))
    if not py_dirs:
        raise RuntimeError("Cannot locate piper venv site-packages")
    return py_dirs[0] / "site-packages"


_PHONEMIZE_NAMES = (
    "phonemize_espeak", "phonemize_codepoints",
    "phoneme_ids_espeak", "phoneme_ids_codepoints",
    "get_codepoints_map", "get_espeak_map", "get_max_phonemes", "tashkeel_run",
)


def _ensure_phonemize_shim():
    """
    Write piper_phonemize shim into the venv if the real C extension isn't
    there, or if a previously-written shim is missing names piper_train
    actually imports (e.g. from an older version of this shim).
    Safe to call on Linux too — skips if the real package already satisfies it.
    """
    probe = "from piper_phonemize import " + ", ".join(_PHONEMIZE_NAMES)
    r = subprocess.run(
        [str(_python()), "-c", probe],
        capture_output=True, timeout=15,
    )
    if r.returncode == 0:
        return  # real piper_phonemize (or an up-to-date shim) already satisfies this

    sp = _site_packages()
    shim_dir = sp / "piper_phonemize"
    shim_dir.mkdir(exist_ok=True)
    (shim_dir / "__init__.py").write_text(_SHIM_CODE, encoding="utf-8")

    # Fake dist-info so pip treats piper-phonemize 1.1.0 as already installed
    dist_info = sp / "piper_phonemize-1.1.0.dist-info"
    dist_info.mkdir(exist_ok=True)
    (dist_info / "METADATA").write_text(
        "Metadata-Version: 2.1\nName: piper-phonemize\nVersion: 1.1.0\n",
        encoding="utf-8",
    )
    (dist_info / "WHEEL").write_text(
        "Wheel-Version: 1.0\nGenerator: faily-shim\nRoot-Is-Purelib: true\nTag: py3-none-any\n",
        encoding="utf-8",
    )


# ── audio helpers ─────────────────────────────────────────────────────────────

def _resample_to_22k(src: Path, dest: Path):
    audio, sr = sf.read(str(src), dtype="float32", always_2d=False)
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    if sr != _SR:
        audio = sps.resample_poly(audio, _SR, sr).astype(np.float32)
    sf.write(str(dest), audio, _SR)


def _prep_dataset(clips: list[dict], dataset_dir: Path) -> int:
    wavs_dir = dataset_dir / "wavs"
    wavs_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for i, entry in enumerate(clips):
        transcript = entry.get("transcript", "").strip()
        if not transcript:
            continue
        stem = f"clip_{i:04d}"
        _resample_to_22k(entry["audio"], wavs_dir / f"{stem}.wav")
        rows.append((stem, transcript))
    with open(dataset_dir / "metadata.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f, delimiter="|").writerows(rows)
    return len(rows)


async def _stream(cmd: list[str], log_cb, proc_ref: list):
    log_cb(f"$ {' '.join(cmd)}")
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )
    proc_ref[0] = proc
    log_cb(f"[pid {proc.pid}] started")
    tail: list[str] = []
    n_lines = 0
    async for raw in proc.stdout:
        line = raw.decode(errors="replace").rstrip()
        log_cb(line)
        n_lines += 1
        tail.append(line)
        if len(tail) > 40:
            tail.pop(0)
    await proc.wait()
    proc_ref[0] = None
    log_cb(f"[pid {proc.pid}] exited {proc.returncode} ({n_lines} output lines)")
    if proc.returncode not in (0, -15):
        detail = "\n".join(tail).strip()
        step = cmd[2] if len(cmd) > 2 and cmd[1] == "-m" else cmd[0]
        raise RuntimeError(
            f"{step} exited {proc.returncode}" + (f":\n{detail}" if detail else "")
        )


async def _probe(py: str, label: str, code: str, log_cb) -> None:
    """Run a quick `python -c <code>` in the piper venv and log the outcome.
    Used for pre-flight checks so import-chain breaks show up immediately
    with a clear label, instead of surfacing later inside a much longer
    preprocess/train subprocess log.

    The blocking subprocess.run() runs in a worker thread — Faily (like most
    asyncio UI apps) runs everything on a single event loop, so a blocking
    call here would freeze the whole server, including the websocket pings
    that keep the browser connected, for its full duration (up to the 30s
    timeout). log_cb runs back on the main thread after the await, since
    NiceGUI elements aren't safe to touch from a worker thread.
    """
    r = await asyncio.to_thread(
        subprocess.run, [py, "-c", code], capture_output=True, timeout=30, text=True
    )
    if r.returncode == 0:
        out = r.stdout.strip()
        log_cb(f"[probe:{label}] OK" + (f" — {out}" if out else ""))
    else:
        detail = (r.stderr or r.stdout or "").strip().splitlines()
        log_cb(f"[probe:{label}] FAILED — {detail[-1] if detail else f'exit {r.returncode}'}")


# ── public API ────────────────────────────────────────────────────────────────

async def train(
    clips: list[dict],
    char_dir: Path,
    log_cb,
    proc_ref: list,
    max_epochs: int = 1000,
) -> Path:
    """Train piper voice model. Streams log lines via log_cb. Returns .onnx path."""
    log_cb(f"Character dir: {char_dir}")
    log_cb(f"Clips received: {len(clips)}")

    reason = await asyncio.to_thread(diagnose)
    if reason:
        raise RuntimeError(f"Piper not ready — {reason}")
    log_cb("Piper venv OK")

    usable = [c for c in clips if c.get("transcript", "").strip()]
    log_cb(f"Usable clips (with transcript): {len(usable)}/{len(clips)}")
    if len(usable) < 2:
        raise ValueError(
            f"Need ≥2 clips with transcripts (have {len(usable)}/{len(clips)}). "
            "Add transcripts via the EDIT button on each ref clip."
        )

    base_ckpts = sorted(PIPER_CKPTS.glob("*.ckpt")) if PIPER_CKPTS.exists() else []
    base_cfgs  = sorted(PIPER_CKPTS.glob("*.json")) if PIPER_CKPTS.exists() else []
    if not base_ckpts:
        raise RuntimeError("No base checkpoint in piper_checkpoints/ — run setup script first")
    if not base_cfgs:
        raise RuntimeError("No .onnx.json config in piper_checkpoints/ — run setup script first")
    log_cb(f"Base checkpoint: {base_ckpts[-1].name}")
    log_cb(f"Base config: {base_cfgs[-1].name}")

    await asyncio.to_thread(_ensure_phonemize_shim)
    log_cb("piper_phonemize shim ready")

    dataset_dir = char_dir / "piper_dataset"
    train_dir   = char_dir / "piper_train"
    train_dir.mkdir(parents=True, exist_ok=True)
    log_cb(f"Dataset dir: {dataset_dir}")
    log_cb(f"Train dir: {train_dir}")

    py = str(_python())
    log_cb(f"Python: {py}")
    log_cb("Running pre-flight import checks…")
    await _probe(py, "torch", "import torch; print(torch.__version__)", log_cb)
    await _probe(
        py, "cuda",
        "import torch; print('available' if torch.cuda.is_available() else 'NOT AVAILABLE — training will fail or fall back to CPU')",
        log_cb,
    )
    await _probe(py, "pytorch_lightning", "import pytorch_lightning; print(pytorch_lightning.__version__)", log_cb)
    await _probe(py, "piper_train.vits.lightning", "import piper_train.vits.lightning", log_cb)

    n = await asyncio.to_thread(_prep_dataset, usable, dataset_dir)
    log_cb(f"Dataset ready: {n} clips")

    # preprocess.py computes batch_size = num_utterances // (max_workers * 2)
    # and errors out ("n must be at least one") if that hits 0 — which it does
    # for small datasets (a handful of ref clips) on any machine with more than
    # a few CPU cores, since it defaults max_workers to os.cpu_count(). Cap it
    # so batch_size always comes out >= 1.
    max_workers = max(1, min(os.cpu_count() or 4, n // 2))
    log_cb(f"Preprocessing (phonemization)… max-workers={max_workers}")
    await _stream([
        py, "-m", "piper_train.preprocess",
        "--language", "en-us",
        "--input-dir",  str(dataset_dir),
        "--output-dir", str(train_dir),
        "--sample-rate", str(_SR),
        "--dataset-format", "ljspeech",
        "--single-speaker",
        "--max-workers", str(max_workers),
    ], log_cb, proc_ref)
    log_cb("Preprocessing done")

    # The base checkpoint already has a current_epoch baked in from its own
    # original training run (Lightning's default naming embeds it: e.g.
    # "epoch=2164-...ckpt"). --max_epochs is an ABSOLUTE target, not a count
    # of additional epochs — passing our max_epochs directly would set a
    # target already in the past and Lightning refuses to resume
    # ("You restored a checkpoint with current_epoch=2164, but you have set
    # Trainer(max_epochs=1000)"). Treat our max_epochs as "how many more
    # epochs to fine-tune for" and add it on top of the checkpoint's epoch.
    m = re.search(r"epoch=(\d+)", base_ckpts[-1].name)
    base_epoch = int(m.group(1)) if m else 0
    target_epochs = base_epoch + max_epochs
    log_cb(
        f"Training — {max_epochs} additional epochs (base checkpoint at epoch "
        f"{base_epoch}, target {target_epochs}), batch 16, GPU, resuming from "
        f"{base_ckpts[-1].name}…"
    )
    await _stream([
        py, "-m", "piper_train",
        "--dataset-dir", str(train_dir),
        "--accelerator", "gpu",
        "--devices", "1",
        "--batch-size", "16",
        "--validation-split", "0.0",
        "--num-test-examples", "0",
        "--max_epochs", str(target_epochs),
        "--resume_from_checkpoint", str(base_ckpts[-1]),
        "--checkpoint-epochs", "100",
        "--precision", "32",
        "--default_root_dir", str(train_dir),
    ], log_cb, proc_ref)
    log_cb("Training done")

    ckpts = sorted(train_dir.rglob("*.ckpt"), key=lambda p: p.stat().st_mtime)
    log_cb(f"Checkpoints found: {len(ckpts)}")
    if not ckpts:
        raise RuntimeError("Training finished but no checkpoint was written")
    log_cb(f"Using checkpoint: {ckpts[-1]}")

    onnx_path = char_dir / "piper.onnx"
    log_cb("Exporting to ONNX…")
    await _stream([
        py, "-m", "piper_train.export_onnx",
        str(ckpts[-1]), str(onnx_path),
    ], log_cb, proc_ref)
    log_cb(f"ONNX export done: {onnx_path}")

    shutil.copy2(str(base_cfgs[-1]), str(char_dir / "piper.onnx.json"))
    log_cb(f"✓  {onnx_path.name}")
    return onnx_path


def infer(text: str, model_path: Path, out_path: Path) -> Path:
    """Blocking piper inference. Returns out_path."""
    cfg = model_path.with_suffix(".onnx.json")
    if not cfg.exists():
        raise FileNotFoundError(f"Piper config missing: {cfg}")
    piper = _piper_bin()
    if not piper.exists():
        raise FileNotFoundError(f"Piper binary missing: {piper}")
    result = subprocess.run(
        [str(piper), "--model", str(model_path), "--config", str(cfg), "--output_file", str(out_path)],
        input=text.encode(),
        capture_output=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Piper: {result.stderr.decode()}")
    return out_path
